### ISSUE TITLE
Upgrade to 3.0

### ISSUE THREAD

**Issue by adambray** [YaleSTC/shifts#137]
# Umbrella issue for Rails 3 upgrade
## From Rails Upgrade Checklist
- [x] `git checkout -b oh-noes-here-we-goes`
- [x] Use the Rails 3.0 upgrade tool RailsCast to overwrite your current application
- [x] Get your Gemfile in order, attempting to load rails console as you go @AdamMcIlravey (related to all the plugins issues below)
- [x] Update your ActiveRecord queries to the new syntax @AdamMcIlravey
- [x] Loading rails console is a huge deal: Have a {chocolate,whiskey,beers} (all of us)
- [x] If your pages load, that means you have a somewhat functioning rails 3.0 application. Commit your changes and get it on heroku for your staff/helpers/friends&family to go to
- [x] Update your mailers to the new syntax @IDlOT 
### Upgrading
- [x] Convert plugins to gems @AdamMcIlravey #135, #134 , #133, #132, #131, #130, #129, #128, #127, #126
- [x] Verify that all necessary plugins have been replaced with gems @mnquintana
- [ ] Routes (upgrade, change syntax where necessary) @AdamMcIlravey 
- [x] Replace polymorphic functionality with simple associations #139 @hkocinneide @adambray 
- [x] Move JS out of views @hkocinneide  #140
- [ ] Change rjs files to erb, with the accompanying prototype to jQuery change @hkocinneide
- [x] Figure out a new implementation for tooltips under a supported library @hkocinneide @adambray 
- [x] Switch from ar_mailer to delayed_job @IDlOT #145 
### Getting to Rails 3.2 (on branch rails-3.2)
- [x] upgrade your gem file to 3.2.13
- [x] Add these gems to your Gemfile under a new "assets group"
- [x] Move your public/images to app/assets/images
- [x] Move your public/stylesheets to app/assets/stylesheets
- [x] Move your public/javascripts to app/assets/javascripts
- [ ] replace prototype datepicker.js 
- [x] Go through your stylesheets and look for urls(); if local, replace with image-url() (Sass)
- [x] Remove any layouts that individually call stylesheets and javascripts
- [x] See if your pages start to break open and swallow you whole
- [x] Remove jQuery
- [x] move your JavaScript libs (underscore, etc) to vendor/assets
- [x] build your application.scss and application.js --- don't put code in these files, just require other files (or load the entire tree)
- [ ] find the problems when you're loading every CSS and JS on every page --- it's very common and you might need to change your application to be nicer
- [x] Use RailsDiff to identify additional required configuration changes
- [ ] commit and push to test instance on Rails farm. do a little dance if it loads. ask for feedback
- [ ] fix the mess that is tooltip.js (maybe go back in time and find the old js code that was embedded in the individual views). aka Regain the class and id distinctions that existed in the Rails 2.3 version. This is to make sure that administrative tools and student tech front ends work properly. #144 
### Refactoring
- [x] Simplify time implementation #138
