### ISSUE TITLE
Things to be fixed before merging instances 

### ISSUE THREAD

**Issue by derekzhao** [YaleSTC/shifts#206]
## General
- [ ] "default role to view" setting for admins so we always see one role #298
## Payforms
- [ ] ability to filter payforms by role so the payform approver only has to see payforms from students that they manage #299
## Stats
- [ ] ability to filter stats view by role OR add role as a column #300
- [ ] ability to selectively send shift stats based on role #301
## Calendar
- [ ] use show/hide groups for timeslot calendar view (similar to schedule view filtering) #302
- [ ] ability to filter calendars.  "Show/Hide Groups" on the Calendars view doesn't work on /acr #307
## Admin
- [x] ability to sort Users list by role #303
- [x] ability to add links to locations/groups, not only department wide #306
- [x] ability to filter Tasks by location group #304
- [x] ability to sort notices by location group #305
