### ISSUE TITLE
META: Ruby v2.x support tracker

### ISSUE THREAD

**Issue by dgoerger** [YaleSTC/shifts#289]
- [x] #258: Debugger doesn't work with Ruby 2.0.0+ 
- [ ] #288: Use gem 'jcrop-rails-v2'
- [x] #291: Don't need gem 'rack-webconsole'

_[please add to this checklist as needed]_
